version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.5.1

jobs:
  deploy-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy"
  doc-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/generate-documentation
  restart-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy:start"
  rubocop-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-rubocop-analysis
  test-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-rspec-tests:
          suite: 'spec/controllers/repartitor_spec.rb'

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - rubocop-job
      - doc-job:
          requires:
            - rubocop-job
      - test-job:
          requires:
            - rubocop-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master
  daily-restart:
    triggers:
      - schedule:
          cron: "5 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - restart-job