errors:
  common:
    app_key:
      forbidden: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-not-premium'
      required: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-key-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#application-key-not-found'
    token:
      required: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#gateway-token-not-given'
      unknown: 'https://github.com/jdr-tools/wiki/wiki/Common-errors#gateway-token-not-found'
  messages:
    account_id:
      unknown: ''
    any_id:
      required: ''
    campaign_id:
      unknown: ''
    message:
      require: ''
    receiver:
      required: ''